### ISSUE TITLE
Reference Genome for correctGC

### ISSUE THREAD

**Issue by ramayyala** [hoangtn/CNVrd2#4]
I am trying to use a different reference genome for the correctGC rather than the default human reference genome UCSC hg19 . I have looked through the pdf manual which says to do so I have to supply my own reference genome. How do i that? There doesn't seem to be a clear input command for in the CNVrd2 function. Also what is the file format for the reference genome/how did you compile your reference genome?

**Comment by hoangtn** [comment]
Hi! 
You can learn how to build genome packages from Bioconductor:
http://bioconductor.org/packages/release/bioc/html/BSgenome.html
Best,
H
